parameters:
  secret: secret

services:
  # temp overwrite until it is merged upstream
  matthias_symfony_console_form.form_helper:
    class: ModuleGenerator\CLI\Console\Helper\FormHelper
    public: false
    arguments:
        - "@matthias_symfony_console_form.console_form_factory"
        - "@matthias_symfony_console_form.delegating_interactor"
    tags:
        - { name: console_helper }

  module-generator_update_service:
    class: ModuleGenerator\CLI\Service\ModuleGenerator\Update
    arguments:
      - '%vendor_directory%/..'

  module-generator_update:
    class: ModuleGenerator\CLI\Console\ModuleGenerator\Update
    arguments:
      - '@module-generator_update_service'
    tags:
      - { name: console.command }

  generate_generate_service:
    class: ModuleGenerator\CLI\Service\Generate\Generate
    arguments:
      - '@templating'

  generate_domain_value-object:
    class: ModuleGenerator\CLI\Console\Generate\Domain\ValueObject
    arguments:
      - '@generate_generate_service'
    tags:
      - { name: console.command }

  generate_domain_image:
    class: ModuleGenerator\CLI\Console\Generate\Domain\Image
    arguments:
      - '@generate_generate_service'
    tags:
      - { name: console.command }

  generate_domain_file:
    class: ModuleGenerator\CLI\Console\Generate\Domain\File
    arguments:
      - '@generate_generate_service'
    tags:
      - { name: console.command }

  generate_domain_crud-commands:
    class: ModuleGenerator\CLI\Console\Generate\Domain\CRUDCommands
    arguments:
      - '@generate_generate_service'
    tags:
      - { name: console.command }

  generate_module_bootstrap:
    class: ModuleGenerator\CLI\Console\Generate\Module\Bootstrap
    arguments:
      - '@generate_generate_service'
    tags:
      - { name: console.command }

  generate_migration_blog-to-news:
    class: ModuleGenerator\CLI\Console\Generate\Migration\BlogToNews
    arguments:
      - '@generate_generate_service'
    tags:
      - { name: console.command }

framework:
  form:
    csrf_protection: true
  secret: "%secret%"
  csrf_protection: ~
  session:
    handler_id: ~
  templating:
    engines: ['twig']
