parameters:
  secret: secret

services:
  module-generator_update_service:
    class: ModuleGenerator\CLI\Service\ModuleGenerator\Update
    arguments:
      - '%vendor_directory%/..'

  module-generator_settings_service:
    class: ModuleGenerator\CLI\Service\ModuleGenerator\Settings
    arguments:
      - '%kernel.root_dir%/settings.yml'

  module-generator_update:
    class: ModuleGenerator\CLI\Console\ModuleGenerator\Update
    arguments:
      - '@module-generator_update_service'
    tags:
      - { name: console.command }

  generate_generate_service:
    class: ModuleGenerator\CLI\Service\Generate\Generate
    arguments:
      - '@templating'

  generate_domain_value-object:
    class: ModuleGenerator\CLI\Console\Generate\Domain\ValueObject
    arguments:
      - '@generate_generate_service'
      - '@module-generator_settings_service'
    tags:
      - { name: console.command }

  generate_domain_image:
    class: ModuleGenerator\CLI\Console\Generate\Domain\Image
    arguments:
      - '@generate_generate_service'
      - '@module-generator_settings_service'
    tags:
      - { name: console.command }

  generate_domain_repository:
    class: ModuleGenerator\CLI\Console\Generate\Domain\Repository
    arguments:
      - '@generate_generate_service'
      - '@module-generator_settings_service'
    tags:
      - { name: console.command }

  generate_domain_file:
    class: ModuleGenerator\CLI\Console\Generate\Domain\File
    arguments:
      - '@generate_generate_service'
      - '@module-generator_settings_service'
    tags:
      - { name: console.command }

  generate_domain_entity:
    class: ModuleGenerator\CLI\Console\Generate\Domain\Entity
    arguments:
      - '@generate_generate_service'
      - '@module-generator_settings_service'
    tags:
      - { name: console.command }

  generate_domain_crud-commands:
    class: ModuleGenerator\CLI\Console\Generate\Domain\CRUDCommands
    arguments:
      - '@generate_generate_service'
      - '@module-generator_settings_service'
    tags:
      - { name: console.command }

  generate_module_bootstrap:
    class: ModuleGenerator\CLI\Console\Generate\Module\Bootstrap
    arguments:
      - '@generate_generate_service'
      - '@module-generator_settings_service'
    tags:
      - { name: console.command }

  generate_migration_blog-to-news:
    class: ModuleGenerator\CLI\Console\SumoCoders\Migration\BlogToNews
    arguments:
      - '@generate_generate_service'
      - '@module-generator_settings_service'
    tags:
      - { name: console.command }

  sumocoders-docker-config:
    class: ModuleGenerator\CLI\Console\SumoCoders\Docker\Config
    arguments:
      - '@generate_generate_service'
      - '@module-generator_settings_service'
    tags:
      - { name: console.command }

framework:
  form:
    csrf_protection: true
  secret: "%secret%"
  csrf_protection: ~
  session:
    handler_id: ~
  templating:
    engines: ['twig']
