parameters:
  secret: secret

services:
  # temp overwrite until it is merged upstream
  matthias_symfony_console_form.form_helper:
    class: ModuleGenerator\CLI\Console\Helper\FormHelper
    public: false
    arguments:
        - "@matthias_symfony_console_form.console_form_factory"
        - "@matthias_symfony_console_form.delegating_interactor"
    tags:
        - { name: console_helper }

  module-generator_update_service:
    class: ModuleGenerator\CLI\Service\ModuleGenerator\Update
    arguments:
      - '%kernel.root_dir%/..'

  module-generator_update:
    class: ModuleGenerator\CLI\Console\ModuleGenerator\Update
    arguments:
      - '@module-generator_update_service'
    tags:
      - { name: console.command }

  generate_Value-object:
    class: ModuleGenerator\CLI\Console\Generate\ValueObject
    arguments:
      - '%cwd%'
    tags:
      - { name: console.command }

framework:
  form:
    csrf_protection: true
  secret: "%secret%"
  csrf_protection: ~
  session:
    handler_id: ~
